# Generated by Django 6.0 on 2025-12-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário/kg')),
                ('tipo', models.CharField(choices=[('PR', 'Bebida/Comida'), ('PE', 'Pesca esportiva'), ('PK', 'Pesca por quilo')], max_length=2, verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta', models.BooleanField(default=True, verbose_name='Comanda Aberta?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade / kg')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comanda', verbose_name='Comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da comanda',
                'verbose_name_plural': 'Itens da comanda',
            },
        ),
    ]
